//! Rust-authored GPU kernel — beginner-friendly end-to-end example.
//!
//! This is the main SDK path: a GPU kernel written in Rust (no HIP C++),
//! compiled to an AMD `.hsaco` code object at build time, and launched with
//! fully typed host bindings generated automatically by `rocm-oxide-build`.
//!
//! # Two-file structure
//!
//! The SDK separates device code from host code:
//!
//! - **Device kernel** (`device-spike/src/lib.rs`):
//!   Rust `#![no_std]` code compiled for `amdgcn-amd-amdhsa`. Contains
//!   the `#[kernel]` function that runs on the GPU.
//!
//! - **Host code** (this file):
//!   Ordinary Rust that opens the device, loads the compiled kernel, sends
//!   data to the GPU, launches, and reads back results.
//!
//! In the source workspace, `cargo build --features device-spike` runs
//! `rocm-oxide-build`, which compiles the device crate and emits:
//!   - `rocm_oxide_device_spike.hsaco`    — GPU code object
//!   - `rocm_oxide_device_spike.bindings.rs` — typed `DeviceKernels` struct
//!   - `rocm_oxide_device_spike.metadata.json` — argument layout records
//!
//! # Run
//!
//! ```sh
//! cargo run --features device-spike --example hello_gpu_rust
//! ```
//!
//! # Kernel source (in device-spike/src/lib.rs)
//!
//! ```rust,ignore
//! use rocm_oxide_device::prelude::*;
//! use rocm_oxide_kernel::kernel;
//!
//! #[kernel]
//! pub unsafe extern "C" fn vector_add(
//!     out: DeviceSliceMut<f32>,
//!     a:   DeviceSlice<f32>,
//!     b:   DeviceSlice<f32>,
//! ) {
//!     for_each_element(out.len(), |i| {
//!         if let (Some(lhs), Some(rhs)) = (a.read(i), b.read(i)) {
//!             out.set(i, lhs + rhs);
//!         }
//!     });
//! }
//! ```

use rocm_oxide::prelude::*;

// Include the typed host bindings generated by rocm-oxide-build.
//
// This exposes `DeviceKernels`, a struct with one method per `#[kernel]`
// function in device-spike. For example, the `vector_add` kernel becomes:
//
//   pub unsafe fn vector_add(
//       &self,
//       config: LaunchConfig,
//       out: &DeviceBuffer<f32>,
//       a:   &DeviceBuffer<f32>,
//       b:   &DeviceBuffer<f32>,
//   ) -> Result<()>
//
// The build tool validates argument types, buffer lengths, and overlap at
// both build time (metadata cross-check) and at runtime (in the generated method).
mod generated {
    include!(env!("ROCM_OXIDE_DEVICE_BINDINGS"));
}

fn main() -> Result<()> {
    // ── Step 1: open the first AMD GPU ──────────────────────────────────────
    let device = Device::first()?;
    println!(
        "hello_gpu_rust: device {} ({})",
        device.ordinal(),
        device.arch()
    );

    // ── Step 2: load the pre-built Rust kernel ───────────────────────────────
    // `load_embedded` reads the .hsaco bytes baked into the binary at compile
    // time and cross-checks the metadata. No file path needed at runtime.
    let kernels = generated::DeviceKernels::load_embedded(&device)?;

    // ── Step 3: prepare input data ────────────────────────────────────────────
    let n: usize = 1 << 20; // 1 048 576 elements

    let a: Vec<f32> = (0..n).map(|i| i as f32).collect();
    let b: Vec<f32> = (0..n).map(|i| (n - i) as f32).collect();

    // Upload to the GPU. `from_slice` allocates device memory and copies.
    let d_a = DeviceBuffer::from_slice(&a)?;
    let d_b = DeviceBuffer::from_slice(&b)?;

    // Allocate the output buffer (uninitialized; the kernel writes every element).
    let d_out = DeviceBuffer::<f32>::new(n)?;

    // ── Step 4: launch the kernel ─────────────────────────────────────────────
    // The generated launcher:
    //   - picks a 1-D launch config with `.grid_for(n)`
    //   - takes typed `&DeviceBuffer<f32>` or `&GpuArray<f32>` instead of raw pointers
    //   - validates buffer lengths match and buffers don't alias
    //   - builds the HIP argument array and calls hipLaunchKernel
    //
    // SAFETY: we hold d_a, d_b, d_out alive past this call and they don't
    //         alias each other (validated by the generated binding).
    unsafe {
        kernels.vector_add_launcher().grid_for(n).launch(
            &d_out, // out: DeviceSliceMut<f32>
            &d_a,   // a:   DeviceSlice<f32>
            &d_b,   // b:   DeviceSlice<f32>
        )?;
    }

    // ── Step 5: wait for the GPU to finish ────────────────────────────────────
    rocm_oxide::hip::synchronize()?;

    // ── Step 6: download and verify ───────────────────────────────────────────
    let out = d_out.copy_to_vec()?;

    for (i, ((&got, &a_i), &b_i)) in out.iter().zip(&a).zip(&b).enumerate() {
        let expected = a_i + b_i;
        if (got - expected).abs() > f32::EPSILON {
            return Err(Error::InvalidLaunch(format!(
                "mismatch at index {i}: got {got}, expected {expected}"
            )));
        }
    }

    println!(
        "hello_gpu_rust: {} elements verified — Rust-authored kernel passed on {}",
        n,
        device.arch()
    );
    Ok(())
}
